name: peersend-io

services:
  go_server:
    hostname: peersend-server
    restart: unless-stopped
    container_name: go-server
    image: peersend.io/server
    build:
      context: ./server
      dockerfile: Dockerfile
      target: local
    ports:
      - 3600:8080
    environment:
      - APP_ENV=development
    volumes:
      - ./server:/usr/src/app
    networks:
      - peersend-network
    tty: true

  web:
    hostname: peersend-web
    restart: unless-stopped
    container_name: vite-app
    image: peersend.io/web
    build:
      context: ./web
      dockerfile: Dockerfile
      target: local
    ports:
      - 3500:5173
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_SESSION_CODE_EXAMPLE=X-4FGS6H
      - VITE_SERVER_ENDPOINT=ws://localhost:3600/exchange
      - VITE_LOG_LEVEL=debug
    networks:
      - peersend-network
    volumes:
      - ./web:/usr/src/app
      - /usr/src/app/node_modules
    tty: true

networks:
  peersend-network:
    driver: bridge
    name: peersend.io-network
