name: peersend-io

services:
  go_server:
    hostname: signal-server
    restart: unless-stopped
    container_name: go-server
    image: peersend.io/signal
    build:
      context: ./server
      dockerfile: Dockerfile
      target: development
    ports:
      - 3001:8080
    volumes:
      - ./server:/usr/src/app
    networks:
      - peersend-network
    tty: true

  web:
    hostname: peersend-web
    restart: unless-stopped
    container_name: vite-app
    image: peersend.io/client
    build:
      context: ./web
      dockerfile: Dockerfile
      target: development
    ports:
      - 3500:5173
    environment:
      - VITE_SESSION_CODE_EXAMPLE=X-4FGS6H
      - VITE_SERVER_ENDPOINT=ws://192.168.1.8:3001/signal
    networks:
      - peersend-network
    volumes:
      - ./web:/usr/src/app
      - /usr/src/app/node_modules
    tty: true

networks:
  peersend-network:
    driver: bridge
    name: peersend.io-network
