/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActivityLog: typeof import('./src/components/session/ActivityLog.vue')['default']
    AppLogo: typeof import('./src/components/AppLogo.vue')['default']
    BackdropGrayCard: typeof import('./src/components/BackdropGrayCard.vue')['default']
    BackNavigation: typeof import('./src/components/BackNavigation.vue')['default']
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Chip: typeof import('primevue/chip')['default']
    ConnectionDetails: typeof import('./src/components/session/connection-status/ConnectionDetails.vue')['default']
    ConnectionStatus: typeof import('./src/components/session/connection-status/ConnectionStatus.vue')['default']
    ConnectionUpgrade: typeof import('./src/components/session/upgrade-dialog/ConnectionUpgrade.vue')['default']
    ConnectionUpgradeDialog: typeof import('./src/components/session/upgrade-dialog/ConnectionUpgradeDialog.vue')['default']
    ConnectionUpgradeInfo: typeof import('./src/components/session/upgrade-dialog/ConnectionUpgradeInfo.vue')['default']
    CopyToClipboard: typeof import('./src/components/CopyToClipboard.vue')['default']
    CopyValue: typeof import('./src/components/CopyValue.vue')['default']
    DeveloperControls: typeof import('./src/components/session/DeveloperControls.vue')['default']
    DirectConnectionPrompt: typeof import('./src/components/session/connection-state/DirectConnectionPrompt.vue')['default']
    DirectionConnectionPrompt: typeof import('./src/components/session/file-transfer/DirectionConnectionPrompt.vue')['default']
    Divider: typeof import('primevue/divider')['default']
    FileTransfer: typeof import('./src/components/session/file-transfer/FileTransfer.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    MainHeader: typeof import('./src/components/header/MainHeader.vue')['default']
    Message: typeof import('primevue/message')['default']
    Panel: typeof import('primevue/panel')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SessionDeck: typeof import('./src/components/session/SessionDeck.vue')['default']
    SessionHeader: typeof import('./src/components/header/SessionHeader.vue')['default']
    SessionPeers: typeof import('./src/components/session/connection-status/SessionPeers.vue')['default']
    SessionWaiting: typeof import('./src/components/session/connection-type/SessionWaiting.vue')['default']
    StatInformation: typeof import('./src/components/session/connection-status/StatInformation.vue')['default']
    Tag: typeof import('primevue/tag')['default']
    TechnicalDetails: typeof import('./src/components/session/connection-status/TechnicalDetails.vue')['default']
    UpgradeComplete: typeof import('./src/components/session/upgrade-dialog/UpgradeComplete.vue')['default']
    UpgradeDialog: typeof import('./src/components/session/upgrade-dialog/UpgradeDialog.vue')['default']
    UpgradeError: typeof import('./src/components/session/upgrade-dialog/UpgradeError.vue')['default']
    UpgradeInfo: typeof import('./src/components/session/upgrade-dialog/UpgradeInfo.vue')['default']
    WaitingForConnections: typeof import('./src/components/session/connection-state/WaitingForConnections.vue')['default']
    WaitingForHost: typeof import('./src/components/session/connection-state/WaitingForHost.vue')['default']
  }
}
